// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFYAx7viEhcnUUHWf0uXzEKgVEkhtnWWI',
    appId: '1:220783166232:web:451cd4da8ea5269afd946d',
    messagingSenderId: '220783166232',
    projectId: 'shopify-b6d9b',
    authDomain: 'shopify-b6d9b.firebaseapp.com',
    storageBucket: 'shopify-b6d9b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgekYrhsHmtZyg8RALMhQAXUltN5ckJjY',
    appId: '1:220783166232:android:b540fca5fad04a3afd946d',
    messagingSenderId: '220783166232',
    projectId: 'shopify-b6d9b',
    storageBucket: 'shopify-b6d9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASPsQtdgkCWox1FV7uBE7PWJWpQmX5Omw',
    appId: '1:220783166232:ios:e4aa32677bf6d6dbfd946d',
    messagingSenderId: '220783166232',
    projectId: 'shopify-b6d9b',
    storageBucket: 'shopify-b6d9b.firebasestorage.app',
    iosBundleId: 'com.example.shopify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASPsQtdgkCWox1FV7uBE7PWJWpQmX5Omw',
    appId: '1:220783166232:ios:e4aa32677bf6d6dbfd946d',
    messagingSenderId: '220783166232',
    projectId: 'shopify-b6d9b',
    storageBucket: 'shopify-b6d9b.firebasestorage.app',
    iosBundleId: 'com.example.shopify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFYAx7viEhcnUUHWf0uXzEKgVEkhtnWWI',
    appId: '1:220783166232:web:77d9d13f98a40bb2fd946d',
    messagingSenderId: '220783166232',
    projectId: 'shopify-b6d9b',
    authDomain: 'shopify-b6d9b.firebaseapp.com',
    storageBucket: 'shopify-b6d9b.firebasestorage.app',
  );
}
